config/routes.rb
Opencounter::Application.routes.draw do
  root :to => 'panels#intro'

  devise_for :admin_users

  match "api/email/application" => "users#application_email", :via => [:get]
  match "api/email/help" => "users#help_email", :via => [:get]
  match "api/lookup/cic" => "cic_codes#index", :via => [:get]
  match "api/lookup/permit/:zoning/:sic" => "permits#show", :via => [:get]
  match "api/lookup/requirements" => "requirements#index", :via => [:get]
  match '/admin/' => redirect('/admin/applications#index'), :via => [:get]
  match '/help' => 'panels#intro', :via => [:get]

  resources :users, :except => :index
  resources :answers

  match '/sessions/create'  => 'sessions#create', :via => [:get, :post]
  match '/sessions/show'    => "sessions#show", :via => [:get]
  match '/sessions/destroy' => "sessions#destroy", :via => [:get]

  match '/users/add_business' => 'users#add_business', :via => [:get]
    
  namespace :admin do
    
    resources :admin_users
    resources :cic_codes do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :requirements do
      post :sort, on: :collection
    end
    
    resources :cic_code_zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :applications
  end

  get "/about"              => "panels#about" 
  get "/help"               => "panels#help"
  get "/info"               => "panels#info"
  get "/info/*path"          => "panels#info"
  get "/intro"              => "panels#intro"
  get "/intro/*path"         => "panels#intro"
  get "/location"           => "panels#location"
  get "/location/*path"      => "panels#location"
  get "/requirements"       => "panels#requirements"
  get "/requirements/*path"  => "panels#requirements"
  get "/summary"            => "panels#summary"
  get "/welcome"            => "panels#welcome"
 

end

app/models/zoning_district.rb
class ZoningDistrict < ActiveRecord::Base
  has_many :requirement_zoning_districts
  has_many :requirements, :through => :requirement_zoning_districts, :dependent => :destroy, :order => "code ASC"
  has_many :cic_code_zoning_districts, :dependent => :destroy
  has_many :cic_codes, :through => :cic_code_zoning_districts, :dependent => :destroy, :order => "code ASC"
  attr_accessible :code, :description, :home_occ_prohibited, :name
  
  before_save :strip_code
  after_create :create_zoning_district_connections
    
  def permission_name(cic_code_id)
    CicCodeZoningDistrict.cross_reference(cic_code_id, self.id).try(:permission_name)    
  end

  def active_cic_codes
    self.cic_codes.where('permission IN (?)', [1,2,3,4])
  end

  def home_occ_prohibited_name
    home_occ_prohibited ? "Yes" : "No"
  end

  
  private
  
  def strip_code
    self.code.strip
  end
  
  def create_zoning_district_connections
    CicCode.all.each do |cic_code|
      CicCodeZoningDistrict.find_or_create_by_cic_code_id_and_zoning_district_id(cic_code.id, self.id)
    end
  end


end

app/controllers/admin/zoning_districts_controller.rb
class Admin::ZoningDistrictsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin_user!
  can_edit_on_the_spot
  
  def index
    @zoning_districts = ZoningDistrict.all(:order => :code)
  end
  
  def show
    @zoning_district = ZoningDistrict.find(params[:id])
    @cic_code_zoning_districts = @zoning_district.cic_code_zoning_districts.sorted_by_cic_code.paginate(
      :page => params[:page])
  end
  
  def edit
    @zoning_district = ZoningDistrict.find(params[:id])
  end

  def update
    @zoning_district = ZoningDistrict.find(params[:id])
    
    respond_to do |format|
      if @zoning_district.update_attributes(params[:zoning_district])
        format.html { redirect_to admin_zoning_districts_url, notice: 'Zoning District was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def new
    @zoning_district = ZoningDistrict.new
  end
  
  def create
    
  end
  
  def destroy
    @zoning_district = ZoningDistrict.find(params[:id])
    @zoning_district.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_zoning_districts_url }
    end
  end
end

app/helpers/admin/zoning_districts_helper.rb
module Admin::ZoningDistrictsHelper
  
  def check_box_helper(value)
    if value == true
      'X'
    end
  end
end

app/views/admin/zoning_districts/_form.html.erb
<% if @zoning_district.errors.any? -%>
  <div id='error_explanation'>
    <h2><%= pluralize(@zoning_district.errors.count, "error") -%> prohibited this county from being saved:"</h2>
    <ul>
      <% @zoning_district.errors.full_messages.each do |msg| -%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end -%>

<div class="field">
  <%= f.label :code %>
  <%= f.text_field :code %>
</div>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, :rows => 5 %>
</div>

<div class="field">
  <br />
  <%= f.check_box :home_occ_prohibited %> Home Occ Prohibited?
</div>

app/views/admin/zoning_districts/edit.html.erb
<h1>Editing Zoning District</h1>

<%= form_for(:zoning_district, :url => admin_zoning_district_path(@zoning_district), :html => {:method => :put}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f}%>

  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_zoning_districts_path %>
  </div>
<% end -%>

app/views/admin/zoning_districts/index.html.erb
<h1>Zoning Districts</h1>
<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>CIC Codes</th>
      <th>Home Occ. Prohibited?</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% for zone in @zoning_districts %>
    <tr class="<%= cycle("odd", "even") -%>">
      <td><%= zone.code %></td>
      <td><%= zone.name %></td>
      <td width="100px"><%= zone.active_cic_codes.size %></td>
      <td width="130px"><%= on_the_spot_edit zone, :home_occ_prohibited, :type => :checkbox, :display_method => :home_occ_prohibited_name %></td>
      <td width="80px"><%= link_to 'Permissions', admin_zoning_district_path(zone), :class => 'btn btn-mini' %></td>
      <td width="40px"><%= link_to 'Edit', edit_admin_zoning_district_path(zone), :class => 'btn btn-mini' %></td>
      <td width="50px"><%= button_to 'Delete', admin_zoning_district_path(zone), method: :delete, confirm: 'Delete this Zoning District?', :class => 'btn btn-mini btn-danger' %></td>
    </tr>
  <% end %>
</table>

<div>
  <%= link_to 'New Zoning District', new_admin_zoning_district_path, :class => 'btn btn-success' %>
</div>
<br />

app/views/admin/zoning_districts/new.html.erb
<h1>New Zoning District</h1>

<%= form_for(:zoning_district, :url => admin_zoning_districts_path, :html => {:method => :post}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f}%>

  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_zoning_districts_path %>
  </div>
<% end -%>

app/views/admin/zoning_districts/show.html.erb
<h1><%= @zoning_district.code %> &mdash; <%= @zoning_district.name %></h1>
<p><%= @zoning_district.description %></p>

<% if flash[:notice].present? %>
  <div class="flash notice"><%= flash[:notice] %></div>
<% end %>

<%= will_paginate @cic_code_zoning_districts, :container => false %>

<% if @zoning_district.cic_code_zoning_districts.blank? %>
  <p>There are no CIC Codes associated with this Zoning District.</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th>Industry</th>
        <th>Subindustry</th>
        <th>Permission Name / Permit Type</th>
        <th>Explanation (if Unknown)</th>
      </tr>
    </thead>
    <tbody>
      <% for cic_code_zoning_district in @cic_code_zoning_districts %>
          <tr class="<%= cycle("odd", "even") -%>">
            <td>
              <%= link_to cic_code_zoning_district.cic_code.code, edit_admin_cic_code_path(cic_code_zoning_district.cic_code, :zoning_district_id => @zoning_district.id) %>
            </td>
            <td><%= cic_code_zoning_district.cic_code.industry %></td>
            <td><%= cic_code_zoning_district.cic_code.subindustry %></td>
            <td width="30%"><%= on_the_spot_edit cic_code_zoning_district, :permission, :display_text => cic_code_zoning_district.permission_name, :type => :select, :data => [ [1,'Zoning Clearance'], [2,'AUP'], [3,'SUP'], [4,'Prohibited'], [5,'Unknown'] ] %></td>
            <td><%= on_the_spot_edit cic_code_zoning_district, :notes %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>