config/routes.rb
Opencounter::Application.routes.draw do
  root :to => 'panels#intro'

  devise_for :admin_users

  match "api/email/application" => "users#application_email", :via => [:get]
  match "api/email/help" => "users#help_email", :via => [:get]
  match "api/lookup/cic" => "cic_codes#index", :via => [:get]
  match "api/lookup/permit/:zoning/:sic" => "permits#show", :via => [:get]
  match "api/lookup/requirements" => "requirements#index", :via => [:get]
  match '/admin/' => redirect('/admin/applications#index'), :via => [:get]
  match '/help' => 'panels#intro', :via => [:get]

  resources :users, :except => :index
  resources :answers

  match '/sessions/create'  => 'sessions#create', :via => [:get, :post]
  match '/sessions/show'    => "sessions#show", :via => [:get]
  match '/sessions/destroy' => "sessions#destroy", :via => [:get]

  match '/users/add_business' => 'users#add_business', :via => [:get]
    
  namespace :admin do
    
    resources :admin_users
    resources :cic_codes do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :requirements do
      post :sort, on: :collection
    end
    
    resources :cic_code_zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :applications
  end

  get "/about"              => "panels#about" 
  get "/help"               => "panels#help"
  get "/info"               => "panels#info"
  get "/info/*path"          => "panels#info"
  get "/intro"              => "panels#intro"
  get "/intro/*path"         => "panels#intro"
  get "/location"           => "panels#location"
  get "/location/*path"      => "panels#location"
  get "/requirements"       => "panels#requirements"
  get "/requirements/*path"  => "panels#requirements"
  get "/summary"            => "panels#summary"
  get "/welcome"            => "panels#welcome"
 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable, :validatable

  def create
    AdminUser.create(params[:adminuser])
  end

  private
    def adminuser_params
      params.require(:adminuser).permit(:email, :password, :password_confirmation, :remember_me)
    end

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin_user!
  
  def index
    @admin_users = AdminUser.all
  end
  
  def edit
    @admin_user = AdminUser.find(params[:id])
  end
  
  def update
    @admin_user = AdminUser.find(params[:id])
    respond_to do |format|
      if @admin_user.update_attributes(params[:admin_user])
        format.html { redirect_to admin_admin_users_url, notice: 'User was successfully updated'  }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def new
    @admin_user = AdminUser.new
  end
  
  def create
    @admin_user = AdminUser.new(params[:admin_user])
    
    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_admin_users_url, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_admin_users_url }
    end
  end
end

app/helpers/admin/admin_users_helper.rb
module Admin::AdminUsersHelper
end

app/views/admin/admin_users/_form.html.erb
<% if @admin_user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

    <ul>
    <% @admin_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <br />
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div class="field">
  <br />
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="field">
  <br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

app/views/admin/admin_users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(:admin_user, :url => admin_admin_user_path(@admin_user), :html => {:method => :put}) do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>

  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_admin_users_path %>
  </div>
<% end %>

app/views/admin/admin_users/index.html.erb
<div class="page-header">
  <h1>Admin Users</h1>
</div>

<table class="table table-striped">
  <thead>
    <th>Email</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </thead>
  <tbody>
  <% for user in @admin_users %>
    <tr class="<%= cycle("odd", "even") -%>">
      <td><%= user.email %></td>
      <td width="40px"><%= link_to 'Edit', edit_admin_admin_user_path(user), :class => 'btn btn-mini' %></td>
      <td width="60px"><%= button_to 'Delete', admin_admin_user_path(user), :method => :delete, :confirm => 'Delete this User?', :class => 'btn btn-mini btn-danger' %></td>
      
    </tr>
  <% end -%>
  </tbody>
</table>

<div>
  <%= link_to 'New User', new_admin_admin_user_path, :class => 'btn btn-success' %>
</div>

app/views/admin/admin_users/new.html.erb
<h1>New User</h1>

<%= form_for(:admin_user, :url => admin_admin_users_path, :html => {:method => :post}) do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>

  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_admin_users_path %>
  </div>
<% end %>