config/routes.rb
Opencounter::Application.routes.draw do
  root :to => 'panels#intro'

  devise_for :admin_users

  match "api/email/application" => "users#application_email", :via => [:get]
  match "api/email/help" => "users#help_email", :via => [:get]
  match "api/lookup/cic" => "cic_codes#index", :via => [:get]
  match "api/lookup/permit/:zoning/:sic" => "permits#show", :via => [:get]
  match "api/lookup/requirements" => "requirements#index", :via => [:get]
  match '/admin/' => redirect('/admin/applications#index'), :via => [:get]
  match '/help' => 'panels#intro', :via => [:get]

  resources :users, :except => :index
  resources :answers

  match '/sessions/create'  => 'sessions#create', :via => [:get, :post]
  match '/sessions/show'    => "sessions#show", :via => [:get]
  match '/sessions/destroy' => "sessions#destroy", :via => [:get]

  match '/users/add_business' => 'users#add_business', :via => [:get]
    
  namespace :admin do
    
    resources :admin_users
    resources :cic_codes do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :requirements do
      post :sort, on: :collection
    end
    
    resources :cic_code_zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :applications
  end

  get "/about"              => "panels#about" 
  get "/help"               => "panels#help"
  get "/info"               => "panels#info"
  get "/info/*path"          => "panels#info"
  get "/intro"              => "panels#intro"
  get "/intro/*path"         => "panels#intro"
  get "/location"           => "panels#location"
  get "/location/*path"      => "panels#location"
  get "/requirements"       => "panels#requirements"
  get "/requirements/*path"  => "panels#requirements"
  get "/summary"            => "panels#summary"
  get "/welcome"            => "panels#welcome"
 

end

app/models/cic_code.rb
class CicCode < ActiveRecord::Base
  belongs_to :parent, :class_name => "CicCode", :foreign_key => "parent_id"
  has_many :children, :class_name => "CicCode", :foreign_key => "parent_id"
  has_many :cic_code_zoning_districts, :dependent => :destroy
  has_many :zoning_districts, -> { order 'code ASC' }, :through => :cic_code_zoning_districts, :dependent => :destroy
  has_and_belongs_to_many :sic_codes, :uniq => true
  has_many :cic_code_requirements, :dependent => :destroy
  has_many :requirements, -> { order('sort_order ASC') }, :through => :cic_code_requirements
  
  accepts_nested_attributes_for :requirements
  
  before_save :strip_code
  after_create :create_zoning_district_connections
  
  def permission_name(zoning_district_id)
    CicCodeZoningDistrict.cross_reference(self.id, zoning_district_id).try(:permission_name)    
  end
  
  def industry_subindustry
    terms = ''
    terms += industry
    terms += ' - '
    terms += subindustry
    return terms
  end
  
  def search_terms
    terms = ''
    terms += industry + ', ' if industry.present?
    terms += subindustry + ', ' if subindustry.present?
    terms += keywords + ', ' if keywords.present?
    return terms
  end
  
  def requirement_names
    requirement_names = self.requirements.collect {|x| x.name }
    requirement_names.join(', ')
  end
  
  private
  
  def strip_code
    self.code.strip
  end
  
  def create_zoning_district_connections
    ZoningDistrict.all.each do |zoning_district|
      CicCodeZoningDistrict.find_or_create_by_cic_code_id_and_zoning_district_id(self.id, zoning_district.id)
    end
  end
end

app/controllers/admin/cic_codes_controller.rb
class Admin::CicCodesController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin_user!
  can_edit_on_the_spot

  def index
    @cic_codes = CicCode.all
  end
  
  def new
    @cic_code = CicCode.new(params[:cic_code])
  end
  
  def create
    @cic_code = CicCode.new(params[:cic_code])
    
    respond_to do |format|
      if @cic_code.save
        format.html { redirect_to admin_cic_codes_url, notice: 'CIC Code was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def edit
    @cic_code = CicCode.find(params[:id])
    @requirements = Requirement.all(:order => 'jurisdiction, name')
  end

  def update
    params[:cic_code][:requirement_ids] ||= []
    @cic_code = CicCode.find(params[:id])
    @requirements = Requirement.all(:order => 'jurisdiction, name')
    
    respond_to do |format|
      if @cic_code.update_attributes(params[:cic_code])
        format.html { redirect_to admin_cic_codes_url, notice: 'CIC Code was successfully updated.' }          
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @cic_code = CicCode.find(params[:id])
    @cic_code.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_cic_codes_url }
    end
  end
end

app/controllers/cic_codes_controller.rb
require 'fuzzystringmatch'

class CicCodesController < ApplicationController

  def index
    cic_codes = []
    CicCode.all.each do |cic_code|
      cic_codes << {code: cic_code.code, industry: cic_code.industry, subindustry: cic_code.subindustry, industry_subindustry: cic_code.industry_subindustry, keywords: cic_code.search_terms}
    end
    query = params['q'].downcase
    query_distances = Array.new(cic_codes.length)
    terms = query.split(%r{\s+})

    jarow = FuzzyStringMatch::JaroWinkler.create( :pure )

    terms.each_with_index { |term, tindex|
      cic_codes.each_with_index { |cic_code, index|
        cic_code[:query_distance] = 0 if tindex == 0
        cic_code[:query_distance] +=1 unless cic_code[:keywords].try(:downcase).try(:match, term).blank?
        cic_code[:query_distance] += jarow.getDistance(query, cic_code[:keywords].try(:downcase))
      }
    }

    cic_codes = cic_codes.sort{ |a, b| b[:query_distance] <=> a[:query_distance]}

    render :json => cic_codes[0...10]
  end

  def cic_code_params
    params.require(:answer).permit(:code, :industry, :subindustry, :home_occ_prohibited, :keywords, :parent_id, :requirements, :requirement_ids, :requirements_attributes)
  end

end

app/helpers/admin/cic_codes_helper.rb
module Admin::CicCodesHelper
end

app/helpers/cic_codes_helper.rb
module CicCodesHelper
end

app/views/admin/cic_codes/_form.html.erb
<% if @cic_code.errors.any? -%>
  <div id='error_explanation'>
    <h2><%= pluralize(@cic_code.errors.count, "error") -%> prohibited this county from being saved:"</h2>
    <ul>
      <% @cic_code.errors.full_messages.each do |msg| -%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end -%>

<% unless params[:requirements] %>
  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :subindustry %>
    <%= f.text_field :subindustry %>
  </div>

  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_area :keywords, :rows => 5 %>
  </div>

  <div class="field">
    <br />
    <%= f.check_box :home_occ_prohibited %> Home Occ Prohibited?
  </div>
  <br />
<% end %>

<div class="field">
  <h3>Requirements</h3>
  <table>
    <% for requirement in @requirements %>
      <tr>
        <td width="25px"><%= check_box_tag "cic_code[requirement_ids][]", requirement.id, @cic_code.requirements.include?(requirement) %>
        <td width="250px"><%= requirement.name %></td>
        <td><%= requirement.jurisdiction %></td>
      </tr>
    <% end -%>
  </table>
  <br />
</div>

app/views/admin/cic_codes/edit.html.erb
<h1>Editing CIC Code <%= @cic_code.code %></h1>

<%= form_for(:cic_code, :url => admin_cic_code_path(@cic_code, :zoning_district_id => @zoning_district.id), :html => {:method => :put}) do |f| %>
  <% if @cic_code.errors.any? -%>
    <div id='error_explanation'>
      <h2><%= pluralize(@cic_code.errors.count, "error") -%> prohibited this county from being saved:"</h2>
      <ul>
        <% @cic_code.errors.full_messages.each do |msg| -%>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end -%>

  <div class="field">
    <%= f.label :parent %>
    <%= f.select :parent_id, options_from_collection_for_select(@zoning_district.cic_codes, :id, :code, :selected => @cic_code.parent) %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>
  
  <div class="field">
    <%= f.label :subindustry %>
    <%= f.text_field :subindustry %>
  </div>
  
  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_area :keywords, :rows => 5 %>
  </div>
  
  <div class="field">
    <br />
    <%= f.check_box :home_occ_prohibited %> Home Occ Prohibited?
  </div>

  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_zoning_district_path(@zoning_district) %>
  </div>
<% end -%>

app/views/admin/cic_codes/index.html.erb
<div class="page-header">
  <h1>Santa Cruz's industry classification codes <small>[CIC Codes]</small></h1>
  <p>Click on any industry, sub-industry, or keyword to edit it. Your changes will be saved when you click away or hit enter.</p>
</div>

<table class="table table-striped">
  <thead>
    <th>Code</th>
    <th>Industry</th>
    <th>Sub-industry</th>
    <th>Requirements</th>
    <th>Keywords</th>
    <th></th>
  </thead>
  <tbody>
    <% for cic_code in @cic_codes %>
      <tr class="<%= cycle("odd", "even") -%>">
        <td><%= cic_code.code %></td>
        <td><%= cic_code.industry %></td>
        <td><%= cic_code.subindustry %></td>
        <td><%= cic_code.requirement_names %> <%= link_to 'add/edit', edit_admin_cic_code_path(cic_code, :requirements => true) %></td>
        <td><%= on_the_spot_edit cic_code, :keywords %></td>
        <td width="40px"><%= link_to 'Edit', edit_admin_cic_code_path(cic_code), :class => 'btn btn-mini' %></td>
        <td width="50px"><%= button_to 'Delete', admin_cic_code_path(cic_code), :method => :delete, :confirm => 'Delete this CIC Code?', :class => 'btn btn-mini btn-danger' %></td>
        
      </tr>
    <% end -%>
  </tbody>
</table>

<div>
  <%= link_to 'New CIC Code', new_admin_cic_code_path, :class => 'btn btn-success' %>
</div>
<br />

app/views/admin/cic_codes/new.html.erb
<h1>Editing CIC Code <%= @cic_code.code %></h1>

<%= form_for(:cic_code, :url => admin_cic_codes_path, :html => {:method => :post}) do |f| %>
  
  <%= render :partial => 'form', :locals => {:f => f} %>
  
  <div class="actions">
    <br />
    <%= f.submit 'Save', :class => 'btn btn-success btn-large' %>
    &nbsp;&nbsp;
    <%= link_to 'Cancel', admin_cic_codes_path %>
  </div>
<% end -%>