config/routes.rb
Opencounter::Application.routes.draw do
  root :to => 'panels#intro'

  devise_for :admin_users

  match "api/email/application" => "users#application_email", :via => [:get]
  match "api/email/help" => "users#help_email", :via => [:get]
  match "api/lookup/cic" => "cic_codes#index", :via => [:get]
  match "api/lookup/permit/:zoning/:sic" => "permits#show", :via => [:get]
  match "api/lookup/requirements" => "requirements#index", :via => [:get]
  match '/admin/' => redirect('/admin/applications#index'), :via => [:get]
  match '/help' => 'panels#intro', :via => [:get]

  resources :users, :except => :index
  resources :answers

  match '/sessions/create'  => 'sessions#create', :via => [:get, :post]
  match '/sessions/show'    => "sessions#show", :via => [:get]
  match '/sessions/destroy' => "sessions#destroy", :via => [:get]

  match '/users/add_business' => 'users#add_business', :via => [:get]
    
  namespace :admin do
    
    resources :admin_users
    resources :cic_codes do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :requirements do
      post :sort, on: :collection
    end
    
    resources :cic_code_zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :zoning_districts do
      collection do
        put :update_attribute_on_the_spot
        get :get_attribute_on_the_spot
      end
    end
    resources :applications
  end

  get "/about"              => "panels#about" 
  get "/help"               => "panels#help"
  get "/info"               => "panels#info"
  get "/info/*path"          => "panels#info"
  get "/intro"              => "panels#intro"
  get "/intro/*path"         => "panels#intro"
  get "/location"           => "panels#location"
  get "/location/*path"      => "panels#location"
  get "/requirements"       => "panels#requirements"
  get "/requirements/*path"  => "panels#requirements"
  get "/summary"            => "panels#summary"
  get "/welcome"            => "panels#welcome"
 

end

app/views/layouts/_profile.html.erb
<div class="utility" id="profile">

    <h3>Your Saved Info</h3>
    <p>Here's what you've told us so far.</p>

    <dl class="complete">
      <dt>Your Name</dt>
      <dd>[applicant_fname] [applicant_lname] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="partial">
      <dt>Your Name</dt>
      <dd>Your first name is [applicant_fname]. <a href="#">Tell us your last name &rarr;</a></dd>
      <dd>Your last name is [applicant_lname]. <a href="#">Tell us your first name &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Your Name</dt>
      <dd>You haven't told us your name yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Your Email</dt>
      <dd class="complete">[applicant_email] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Your Email</dt>
      <dd class="empty">You haven't told us your email address yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Your Home Address</dt>
      <dd>[applicant_home_address_street], [applicant_home_address_details], [applicant_home_address_city], [applicant_home_address_state] [applicant_home_address_zip] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="complete">
      <dt>Your Home Address</dt>
      <dd>[applicant_home_address_street], [applicant_home_address_city], [applicant_home_address_state] [applicant_home_address_zip] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="partial">
      <dt>Your Home Address</dt>
      <dd>[applicant_home_address_street] <a href="#">Complete this &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Your Home Address</dt>
      <dd>You haven't told us your home address yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Business Name</dt>
      <dd>[business_name] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Business Name</dt>
      <dd>You haven't told us your business name yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Business Type</dt>
      <dd>[business_type] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Business Type</dt>
      <dd>You haven't told us your business type. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Business Structure</dt>
      <dd>[business_structure] <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Business Structure</dt>
      <dd>You haven't told us your business's legal structure yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Ownership</dt>
      <dd>You are the sole owner of this business. <a href="#">Change this &rarr;</a></dd>
    </dl>
    <dl class="complete">
      <dt>Ownership</dt>
      <dd>Apart from you, the following people are involved in this business:
        [coowner_#_fname] [coowner_#_lname] ([coowner_#_role]),
        [coowner_#_fname] [coowner_#_lname] ([coowner_#_role]) <a href="#">Change this &rarr;</a>
      </dd>
    </dl>
    <dl class="partial">
      <dt>Ownership</dt>
      <dd>You've told us you have co-owners, but haven't told us who they are. <a href="#">Fill this out &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Ownership</dt>
      <dd>You haven't told us whether you have co-owners. <a href="#">Fill this out &rarr;</a></dd>
    </dl>

    <dl class="complete">
      <dt>Business Location</dt>
      <dd>You'll be working from home. <a href="#">Fill this out &rarr;</a></dd>
    </dl>
    <dl class="complete">
      <dt>Business Location</dt>
      <dd>You'll be working from [business_location_street], [business_location_detail], [business_location_city], [business_location_state] [business_location_zip]. <a href="#">Fill this out &rarr;</a></dd>
    </dl>
    <dl class="partial">
      <dt>Business Location</dt>
      <dd>You aren't working from home, but haven't told us your business's location yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>
    <dl class="empty">
      <dt>Business Location</dt>
      <dd>You haven't told us your business's location yet. <a href="#">Fill this out &rarr;</a></dd>
    </dl>


      </div>
      <div>
        <h3>Forms &amp; Fees</h3>
        <p>Based on what you've told us so far, we estimate that starting your business will cost <span>$13,543.54</span> (see breakdown)</p>
        <p>Based on what you've told us so far, we think you'll need to complete and submit the following forms:</p>
        <ul>
          <li><a href="">Form 1</a></li>
          <li><a href="">Form 2</a></li>
          <li><a href="">Form 3</a></li>
        </ul>
      </div>
      <div>
        <h3>Next Steps</h3>
        <ol>
          <li>Download, complete, and submit Form 1.</li>
          <li>Download, complete, and submit Form 2.</li>
          <li>Make an appointment with the Planning Department.</li>
          <li>...</li>
          <li>Profit.</li>
        </ol>
      </div>
    </div><!-- /#profile -->

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>OpenCounter - Admin</title>

    <!-- Application styles. -->
    <%= stylesheet_link_tag   "application" %>
    <%= requirejs_include_tag "application" %>

    <%= stylesheet_link_tag :on_the_spot %>

    <%= javascript_include_tag :jquery %>
    <%= javascript_include_tag 'jquery-ui' %>
    <%= javascript_include_tag :on_the_spot %>
    <%= csrf_meta_tag %>
    
    <meta charset="utf-8">
    
  </head>

  <body>
    <div class="container-fluid">
      <div id="admin_header">
        <div style="float: right;">
          <% unless current_user %>
            <%= button_to 'Log Out', destroy_admin_user_session_path, :method => :delete %>
          <% end %>
        </div>
        <div>
          <%= link_to 'Applications', admin_applications_url %> |
          <%= link_to 'CIC Codes', admin_cic_codes_url %> |
          <%= link_to 'Requirements', admin_requirements_url %> |
          <%= link_to 'Users', admin_admin_users_url %> |
          <%= link_to 'Zoning Districts', admin_zoning_districts_url %>
        </div>
      </div>
      <% if notice.present? %>
        <p class="alert alert-success"><%= notice %></p>
      <% elsif alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>OpenCounter - Start your business in Santa Cruz, CA</title>

    <!-- Application styles. -->
    <%= stylesheet_link_tag   "application" %>
    <link href="http://fonts.googleapis.com/css?family=Oswald:300,400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    
  </head>

  <body>
  <!-- Main container. -->
    <div role="main" id="main"></div>

    <!-- Application source. -->
    <script data-main="/assets/app/config" src="/assets/libs/require.js"></script>
    <%= requirejs_include_tag "application" %>
  </body>
</html>